version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoDb
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:27017:${MONGO_INITDB_ROOT_PORT}"
    volumes:
      - ./mongoData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Europe/Moscow
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
