  name: Publish Docker
  on:
    push:
      branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Publish to registery
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            registry: docker.pkg.github.com
            name: docker.pkg.github.com/exact01/helloNestJs/top-api-demo
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "develop"